### ISSUE TITLE
Substitute ${openocd_path} in openocd gui fields

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/eclipse-plugins#246]
https://github.com/gnu-mcu-eclipse/eclipse-plugins/issues/236#issuecomment-340304450

**Comment by ilg-ul** [comment]
fixed since v4.2.1-201711101735

**Comment by asier70** [comment]
Confirmed - it works. Thanks!

**Comment by ilg-ul** [comment]
great, thank you.

**Comment by biswaMW** [comment]
Is this by chance broken in v4.3.2.201804191501 ?
I see : Cannot run program "${openocd_path}/${openocd_executable}": Launching failed

Both the Global and the Workspace paths for OpenOCD are set correctly.
Using those paths directly in the Debug window works though.

Any ideas ?
Running neon.3 with GNU MCU Eclipse 4.3.3

**Comment by ilg-ul** [comment]
I don't remember having this problem in 4.3.2.

Please download the latest version and try again in a clean Eclipse and a clean workspace.

**Comment by TM1234** [comment]
This is not broken for me.
I presume that in the debug launch configuration GUI on the Debugger tab you see Executable path: ${openocd_path}/${openocd_executable}?
What do you see in the Actual executable field and is it correct?

**Comment by biswaMW** [comment]
How do I examine the 'Actual executable field' ?

From the error window this is what I have.
Launching command [${openocd_path}/${openocd_executable} -c gdb_port 3333 -c telnet_port 4444 -c tcl_port 6666 -f board/st_nucleo_f3.cfg -c echo "Started by GNU MCU Eclipse"] failed.

Are the macros resolved internally (i.e. not visible in the error window) ?

**Comment by biswaMW** [comment]
@ilg-ul : I'm sorry I missed the 'Actual executable' field. I do see it. (I was just used to the old plug-in. I recently upgraded my machine and was installing the latest plug-in.).

It contains : ${openocd_path}/${openocd_executable}

If it helps, I'm running Win10, JDK1.8 and already tried a clean re-install with a new workspace.

Thanks for looking into this !

**Comment by ilg-ul** [comment]
you somehow messed your Eclipse and this affect the macro substitutions.

go to both Global/Workspace OpenOCD paths and Restore Defaults.

if this does not help, install in a separate folder the latest Eclipse which includes the latest plug-ins, do not install any other plug-ins, and retry.

**Comment by TM1234** [comment]
You should see something like this (the specific paths will be different so just for illustration):
![gme1](https://user-images.githubusercontent.com/14550604/39575663-468feb82-4ed3-11e8-84da-d703baed8ae1.PNG)
![gme2](https://user-images.githubusercontent.com/14550604/39575664-46b82f34-4ed3-11e8-89b2-2cbe9d5f22eb.PNG)

**Comment by biswaMW** [comment]
@TM1234 @ilg-ul  : Thanks for the suggestions !
After some trial and error, it looks like it isn't an issue with install at all.
It might have to do with my workflow.

I do not use Eclipse to build/develop applications (so I don't create/import projects)
I just create a standalone debug configuration, load an elf, specify the board to OpenOCD and start debugging.
![capture](https://user-images.githubusercontent.com/25658888/39579193-a59b1cf8-4ed5-11e8-8c8f-12eb43624d65.PNG)

-------------------------------------------------------
This time I tried creating (just as an experiment) a new project. Now when I generate a debug configuration associated with this project, the 'Actual Executable' field does indeed populate appropriately and everything works just fine !
![capture1](https://user-images.githubusercontent.com/25658888/39579044-4d866b30-4ed5-11e8-85b7-e4ca267d1cdf.PNG)

I am familiar with the approach to 'import' an elf and create a (non-buildable) project to debug the exec.
So I tried this and it worked as well.

In essence, it looks like a debug config now needs to be associated with a project. 
Is this expected ?
Should I switch to *always* creating projects with the new plugin ?

(I speculate my original workflow was working with the former plug-in since the macros were string substituted, which isn't the case now.)

Boy, was it a long session today and thanks a ton for helping !

**Comment by ilg-ul** [comment]
> it looks like a debug config now needs to be associated with a project.
> Is this expected ?

well, a debug config does not **need** to be associated with a project.

you can always browse for the absolute address of the binaries.

however, the defaults used to create the debug config expect a project, since expanding the macos require a project.

but, as I said, you can always override the devaults with any setting you want.
